---
- name: "install packages"
  dnf:
    name: "*"
    disable_gpg_check: yes
    state: latest

- name: "install packages"
  dnf:
    name:
      - "{{ item }}"
    state: latest
    disable_gpg_check: yes
  loop: "{{ packages }}"
