#cloud-config
# vim:syntax=yaml

### Boot Commands ###

### Timezone ###

timezone: Etc/UTC

### Packages ###

packages:
  - ca-certificates
  - gnupg-agent
  - python3
  - git
  - curl
  - wget
  - jq
  - ansible
  - unzip

### Users and Groups ###

#system_info:
#  default_user:

users:
  - name: ansible
    homedir: /home/ansible
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "ssh-rsa ..."

### Ansible ###

ansible:
  install_method: distro
  package_name: ansible
  # the run_user parameter is only considered if install_method is set to pip
  #run_user: ansible
  #setup_controller:
  #  repositories:
  #    - path: /home/ansible/
  #     source: <playbook_url>
  #  run_ansible:
  #    - playbook_dir: /home/ansible/<playbook_dir>
  #      playbook_name: <playbook_name>
  pull:
    url: "https://oauth2:<GitHub access token>@github.com/thimslugga/cloud-init-bootstrap.git"
    playbook_name: "playbooks/<playbook>.yml"
    #accept_host_key: true

### Run Command ###

# Alternatively you can use the following runcmd
#runcmd:
#- [ python3, -m, pip, install, ansible ]
#- [git, clone, <some magic repo URL>]
#- [ansible-playbook, <magic playbook>]

### Final Message ###

final_message: "The system is finally up, after $UPTIME seconds"

### Output ###

output: { all: "| tee -a /var/log/cloud-init.log" }
