#cloud-config
# vim:syntax=yaml

### Boot Commands ###

#bootcmd:
#  - printf "[Resolve]\nDNS=169.254.169.254" > /etc/systemd/resolved.conf
#  - systemctl restart systemd-resolved

### Timezone ###

timezone: Etc/UTC

### Packages ###

package_update: true
package_upgrade: true
apt_get_command:
  [
    "apt-get",
    "--option=Dpkg::Options::=--force-confold",
    "--option=Dpkg::options::=--force-unsafe-io",
    "--assume-yes",
    "--quiet",
    "--no-install-recommends",
  ]

packages:
  - apt-transport-https
  - software-properties-common
  - ca-certificates
  - gnupg-agent
  - cloud-init
  - ssh-import-id
  - git
  - git-lfs
  - curl
  - wget
  - aria2
  - jq
  - python3
  - python3-venv
  - ansible
  - ansible-lint
  - yamllint
  - dnsutils
  - net-tools
  - zstd
  - p7zip-full
  - tree
  - vim
  - docker-ce
  - docker-ce-cli
  - containerd.io

### Users and Groups ###

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

users:
  - name: ubuntu
    shell: /bin/bash
    groups: [admin, users, wheel]
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_import_id: gh:thimslugga
    #ssh_authorized_keys:
      #- "ssh-rsa ..."
  - name: ansible
    shell: /bin/bash
    groups: [admin, users, wheel]
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_import_id: gh:thimslugga
    #ssh_authorized_keys:
    #  - "ssh-rsa ..."

### Write Files ###

write_files:
  - path: /etc/sysctl.d/99-custom-tuning.conf
    owner: root:root
    permissions: "0644"
    content: |
      # Adjust default kernel printk level from 7 (debug) to 3 (info)
      kernel.printk=3 4 1 7
      # Automatically reboot the system if kernel panics
      kernel.panic=5
      # Enable IP forwarding
      net.ipv4.ip_forward=1
      net.ipv4.conf.all.forwarding=1
      net.ipv6.conf.all.forwarding=1
      net.ipv6.conf.default.forwarding=1
      #net.ipv6.conf.all.accept_redirects=0
      #net.ipv6.conf.all.accept_ra=2
      #net.ipv6.conf.default.accept_ra=2

  - path: /etc/docker/daemon.json
    owner: root:root
    permissions: "0644"
    content: |
      {
        "dns": [
          "1.1.1.1",
          "1.0.0.1"
        ],
        "hosts": ["unix:///var/run/docker.sock"]
      }

  - path: /etc/sudoers.d/90-cloud-init-bootstrap
    owner: root:root
    permissions: "0440"
    content: |
      ubuntu ALL=(ALL) NOPASSWD:ALL
      ansible ALL=(ALL) NOPASSWD:ALL
      #%admin ALL=(ALL) NOPASSWD:ALL
      #%wheel ALL=(ALL) NOPASSWD:ALL

      Defaults:ubuntu !requiretty
      Defaults:ansible !requiretty
      #Defaults:%admin !requiretty
      #Defaults:%wheel !requiretty

  - path: /etc/ansible/hosts
    owner: ansible:ansible
    permissions: "0644"
    defer: true
    content: |
      [all]
      localhost ansible_connection=local
      [all:vars]
      ansible_user=ansible
      ansible_become=yes
      ansible_become_method=sudo
      ansible_python_interpreter=/usr/bin/python3

  - path: /etc/systemd/system/docker.service.d/override.conf
    owner: root:root
    permissions: "0644"
    content: |
      # Disable dockerd flags as all settings should come from the
      # /etc/docker/daemon.json file.
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd

### Final Message ###

final_message: "The system is finally up, after $UPTIME seconds"

### Output ###

output: { all: "| tee -a /var/log/cloud-init.log" }

### Power State ###

# power_state:
#   timeout: 300
#   mode: reboot
