---

- name: Cloud-Init Ansible Bootstrap
  hosts: localhost
  connection: local
  become: true
  vars:
    packages:
      - yum-utils
      - git
      - bzip2
      - zstd
      - unzip
      - ethtool
      - iproute-tc
      - nftables
      - grubby
      - git
      - vim
      - jq
      - ansible
      - docker
      - amazon-ecr-credential-helper
      - oci-add-hooks
      - udica
  roles:
    - dnf
