---

- name: "Install packages"
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: "Install packages"
  ansible.builtin.apt:
    name:
      - "{{ item }}"
    state: latest
  loop: "{{ packages }}"
