---

- name: "Install packages"
  ansible.builtin.yum:
    name: "*"
    state: latest
    disable_gpg_check: true


- name: "Install packages"
  ansible.builtin.yum:
    name:
      - "{{ item }}"
    state: latest
    disable_gpg_check: true
  loop: "{{ packages }}"
